### PR TITLE
[INFRA-103] slim fit

### PR DESCRIPTION
**Pull request by kotchaosu**

### CODE REVIEW

**Comment by 23doors** [comment]
lgtm. how slim is it now anyway?

**Comment by kotchaosu** [comment]
I won't merge it till I have all sandboxes, but looks promising:

```
before/python-codebox   latest              7e3e222ca09e        About an hour ago   811.7 MB
after/python-codebox      latest              fcca1c2f3de4           5 seconds ago         787.5 MB
```

**Comment by 23doors** [comment]
Well, not much slimmer, but if they all share one common base image (which is most likely a bigger portion of total size) then we will save quite a lot.

**Comment by 23doors** [comment]
Consider a less bloated and arguably more stable distro - ubuntu 14.04. Debian in my experience has a history of pretty slow security and other package fixes.
Also `523.7 MB`. So 264MB less that this.
https://github.com/Syncano/python-codebox/pull/22

**Pull request merged**
