### PR TITLE
[INFRA-158] SciPy and NumPy

### PR DESCRIPTION
**Pull request by kotchaosu**
painful image size overhead, but...

```
python-codebox                     latest              2b0e8c634b73        About an hour ago   815.1 MB
quay.io/syncano/python-codebox     latest              b573b3705f37        2 weeks ago         500.2 MB
```

### CODE REVIEW

**Comment by 23doors** [comment]
Huh. A big one. Seems like one of the modules that wouldn't even fit in 50mb limit for all packages. From what I checked - numpy is roughly 20MB and scipy 70MB. Guess we should consider supporting such big packages in the future by default then but it's not like there are many packages like that. Looks good!

**Comment by kotchaosu** [comment]
@23doors I'm testing also installing those packages via apt. The problem is those libs demand low-level support (blas and lapack) - extra size is determined mostly by dependencies.

**Comment by kotchaosu** [comment]
@23doors check this out

```
python-codebox2                    latest              ea44256547ef        4 minutes ago       601.5 MB
python-codebox                     latest              2b0e8c634b73        3 hours ago         815.1 MB
quay.io/syncano/python-codebox     latest              b573b3705f37        2 weeks ago         500.2 MB
```

**Comment by 23doors** [comment]
image

Anyway it seems in line with library sizes, no g++ and dev packages overhead, just libs which are roughly 100mb when I checked.

**Comment by kotchaosu** [comment]
:D kind of magic I prefer

**Pull request merged**
