### PR TITLE
Add mixpanel

### PR DESCRIPTION
**Pull request by MariuszWisniewski**
@Zhebr I was a bit confused to which requirements file to add it... Hope it's ok.

### CODE REVIEW

**Comment by 23doors** [comment]
Should we continue adding libraries to old/deprecated runtimes?

**Comment by MariuszWisniewski** [comment]
`¯\_(ツ)_/¯`
I'm fine with only new and both new and old.

**Comment by kotchaosu** [comment]
@lifcio I don't think adding new stuff do deprecated runtime is a good idea. Are there necessary for old stuff?

**Comment by MariuszWisniewski** [comment]
No, they're not, I want to use it in new Scripts. If that's the decision I'll remove it from 4.2

**Comment by kotchaosu** [comment]
Let's keep it in new requirements then.

**Comment by MariuszWisniewski** [comment]
Done. Sorry it took so long

**Comment by 23doors** [comment]
looks good

**Pull request merged**
