### PR TITLE
Add Fastly package

### PR DESCRIPTION
**Pull request by MariuszWisniewski**
https://github.com/fastly/fastly-py

### CODE REVIEW

**Comment by kotchaosu** [comment]
from CI

```
  Could not find a version that satisfies the requirement fastly==0.0.3 (from -r /tmp/requirements.txt (line 23)) (from versions: 0.0.2)
No matching distribution found for fastly==0.0.3 (from -r /tmp/requirements.txt (line 23))
```

**Comment by MariuszWisniewski** [comment]
Thanks, will take a look.

**Comment by MariuszWisniewski** [comment]
On pip indeed there's 0.0.2 version, I was sure there's 0.0.3 looking at: https://pypi.python.org/pypi/fastly , my mistake!

**Comment by MariuszWisniewski** [comment]
@Zhebr Can be merged now?

**Comment by kotchaosu** [comment]
@lifcio sure

**Pull request merged**
