### PR TITLE
[slim_fit] Ubuntu version

### PR DESCRIPTION
**Pull request by 23doors**
`523.7 MB`

### CODE REVIEW

**Comment by kotchaosu** [comment]
wooow - I'm testing it now - looks promising

**Comment by kotchaosu** [comment]
sadly

```
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> 
>>> import aexol
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/aexol/__init__.py", line 1, in <module>
    from .ocr_detector import *
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/local/lib/python2.7/dist-packages/aexol/libocr_detection.so)
>>> 
```

but I think it's simple to solve

**Comment by kotchaosu** [comment]
neat

**Comment by 23doors** [comment]
For them or for us? ;) For them it is most likely a matter of recompiling it with different glibc.

**Comment by kotchaosu** [comment]
Yes, will inform about the issue, when I have all images done.

**Pull request merged**
